# Generated by Django 6.1.1 on 2026-10-06 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_taskattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('project_created', 'Project created'), ('project_updated', 'Project updated'), ('project_archived', 'Project archived'), ('project_restored', 'Project restored'), ('task_created', 'Task created'), ('task_updated', 'Task updated'), ('task_deleted', 'Task deleted'), ('task_status_changed', 'Task status changed'), ('attachment_uploaded', 'Attachment uploaded'), ('attachment_deleted', 'Attachment deleted')], max_length=40)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskflow_activities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='projects.task')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
