# Generated by Django 6.1.1 on 2026-10-06 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='changes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='activity',
            name='subject_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='activity',
            name='subject_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='subject_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('relation_changed', 'Relation changed'), ('project_created', 'Project created'), ('project_updated', 'Project updated'), ('project_archived', 'Project archived'), ('project_restored', 'Project restored'), ('task_created', 'Task created'), ('task_updated', 'Task updated'), ('task_deleted', 'Task deleted'), ('task_status_changed', 'Task status changed'), ('attachment_uploaded', 'Attachment uploaded'), ('attachment_deleted', 'Attachment deleted')], max_length=40),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='projects.project'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['subject_type', 'subject_id'], name='activity_subject_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['action', 'created_at'], name='activity_action_date_idx'),
        ),
    ]
